Repository Move-Log/Move-Log-Server, pull requests merged in 2025-01, with the labels that each got.

#17 [DOCS] AUTH 관련 API 명세서 수정
  src/main/resources/static/openapi.json
Labels: docs 📄

#19 [FEAT] 회원가입 로직 추가
  src/main/java/com/movelog/domain/auth/application/AuthService.java
  src/main/java/com/movelog/domain/auth/presentation/AuthController.java
  src/main/java/com/movelog/domain/user/domain/User.java
Labels: feature ✨

#21 [FEAT] S3, 도메인 설정
  build.gradle
  src/main/java/com/movelog/MoveLogApplication.java
  src/main/java/com/movelog/domain/common/BaseEntity.java
  src/main/java/com/movelog/domain/common/Status.java
  src/main/java/com/movelog/domain/record/domain/Keyword.java
  src/main/java/com/movelog/domain/record/domain/Record.java
  src/main/java/com/movelog/domain/record/domain/VerbType.java
  src/main/java/com/movelog/domain/user/domain/User.java
  src/main/java/com/movelog/global/config/WebClientConfig.java
  src/main/java/com/movelog/global/config/security/AmazonS3Config.java
  src/main/java/com/movelog/global/util/S3Util.java
Labels: feature ✨

#22 [DOCS] API 명세서 내 배포 주소 정보 수정
  src/main/resources/static/openapi.json
Labels: docs 📄

#34 [FIX] 토큰시간 1달로 변경
  src/main/java/com/movelog/domain/auth/presentation/AuthController.java
Labels: fix 🔧

#35 Merge main to develop
  Dockerfile
Labels: CICD

#37 [CICD] CICD 구축에 따른 충돌 방지를 위한 PR
  .github/workflows/deploy.yml
  Dockerfile
  appspec.yml
Labels: CICD 🦋

#40 [FEAT] 뉴스 헤드라인 추천 기능 구현
  src/main/java/com/movelog/domain/gpt/application/GptService.java
  src/main/java/com/movelog/domain/news/application/HeadlineGeneratorService.java
  src/main/java/com/movelog/domain/news/application/NewsService.java
  src/main/java/com/movelog/domain/news/dto/request/NewsHeadLineReq.java
  src/main/java/com/movelog/domain/news/dto/response/HeadLineRes.java
  src/main/java/com/movelog/domain/news/presentation/NewsController.java
  src/main/java/com/movelog/domain/user/application/UserService.java
  src/main/java/com/movelog/domain/user/exception/UserDuplicateException.java
  src/main/java/com/movelog/domain/user/exception/UserNotFoundException.java
  src/main/java/com/movelog/global/exception/DuplicateException.java
  src/main/java/com/movelog/global/exception/NotFoundException.java
  src/main/resources/static/openapi.json
Labels: feature ✨

#42 [REFACTOR] VerbType enum 사용에 따른 기록 생성 기능 수정
  src/main/java/com/movelog/domain/record/domain/Record.java
  src/main/java/com/movelog/domain/record/domain/VerbType.java
  src/main/java/com/movelog/domain/record/dto/request/CreateRecordReq.java
  src/main/java/com/movelog/domain/record/presentation/RecordController.java
  src/main/java/com/movelog/domain/record/service/RecordService.java
Labels: refactor 🍀

#43 Merge develop to main
  src/main/java/com/movelog/domain/auth/presentation/AuthController.java
  src/main/java/com/movelog/domain/gpt/application/GptService.java
  src/main/java/com/movelog/domain/news/application/HeadlineGeneratorService.java
  src/main/java/com/movelog/domain/news/application/NewsService.java
  src/main/java/com/movelog/domain/news/dto/request/NewsHeadLineReq.java
  src/main/java/com/movelog/domain/news/dto/response/HeadLineRes.java
  src/main/java/com/movelog/domain/news/presentation/NewsController.java
  src/main/java/com/movelog/domain/record/domain/Record.java
  src/main/java/com/movelog/domain/record/domain/VerbType.java
  src/main/java/com/movelog/domain/record/dto/request/CreateRecordReq.java
  src/main/java/com/movelog/domain/record/presentation/RecordController.java
  src/main/java/com/movelog/domain/record/service/RecordService.java
  src/main/java/com/movelog/domain/user/application/UserService.java
  src/main/java/com/movelog/domain/user/exception/UserDuplicateException.java
  src/main/java/com/movelog/domain/user/exception/UserNotFoundException.java
  src/main/java/com/movelog/global/exception/DuplicateException.java
  src/main/java/com/movelog/global/exception/NotFoundException.java
  src/main/resources/static/openapi.json
Labels: feature ✨, refactor 🍀

#45 Merge develop to main
  src/main/java/com/movelog/domain/record/presentation/RecordController.java
Labels: refactor 🍀

#49 [FEAT] 뉴스 생성 시 사용된 최근 키워드(동사-명사) 조회 기능 구현
  src/main/java/com/movelog/domain/news/application/NewsService.java
  src/main/java/com/movelog/domain/news/dto/response/RecentKeywordsRes.java
  src/main/java/com/movelog/domain/news/presentation/NewsController.java
  src/main/java/com/movelog/domain/record/repository/KeywordRepository.java
Labels: feature ✨

#52 [FEAT] 최근 기록 이미지 목록 조회 기능 구현
  src/main/java/com/movelog/domain/news/presentation/NewsController.java
  src/main/java/com/movelog/domain/record/domain/Keyword.java
  src/main/java/com/movelog/domain/record/dto/response/RecentRecordImagesRes.java
  src/main/java/com/movelog/domain/record/dto/response/TodayRecordStatus.java
  src/main/java/com/movelog/domain/record/presentation/RecordController.java
  src/main/java/com/movelog/domain/record/repository/KeywordRepository.java
  src/main/java/com/movelog/domain/record/repository/RecordRepository.java
  src/main/java/com/movelog/domain/record/service/RecordService.java
Labels: enhancement, feature ✨, fix 🔧

#57 [FEAT] 뉴스 생성에 사용될 사용자 기록 명사 검색 기능 구현
  src/main/java/com/movelog/domain/record/dto/request/SearchKeywordReq.java
  src/main/java/com/movelog/domain/record/dto/response/SearchKeywordRes.java
  src/main/java/com/movelog/domain/record/presentation/RecordController.java
  src/main/java/com/movelog/domain/record/repository/KeywordRepository.java
  src/main/java/com/movelog/domain/record/service/RecordService.java
Labels: feature ✨

#58 [FEAT] 사용자가 최근 7일간 생성한 뉴스 목록 조회 기능 구현
  src/main/java/com/movelog/domain/news/application/NewsService.java
  src/main/java/com/movelog/domain/news/domain/repository/NewsRepository.java
  src/main/java/com/movelog/domain/news/dto/response/RecentNewsRes.java
  src/main/java/com/movelog/domain/news/presentation/NewsController.java
Labels: feature ✨

#59 Merge develop to main
  src/main/java/com/movelog/domain/news/application/NewsService.java
  src/main/java/com/movelog/domain/news/domain/repository/NewsRepository.java
  src/main/java/com/movelog/domain/news/dto/response/RecentNewsRes.java
  src/main/java/com/movelog/domain/news/presentation/NewsController.java
  src/main/java/com/movelog/domain/record/dto/request/SearchKeywordReq.java
  src/main/java/com/movelog/domain/record/dto/response/SearchKeywordRes.java
  src/main/java/com/movelog/domain/record/presentation/RecordController.java
  src/main/java/com/movelog/domain/record/repository/KeywordRepository.java
  src/main/java/com/movelog/domain/record/service/RecordService.java
Labels: feature ✨, CICD 🦋

#60 [DOCS] 페이징 관련 명세 수정
  src/main/java/com/movelog/domain/news/presentation/NewsController.java
Labels: docs 📄

#61 Merge develop to main
  src/main/java/com/movelog/domain/news/presentation/NewsController.java
Labels: docs 📄

#62 [FEAT] 뉴스 현황 조회 기능 및 날짜별 뉴스 목록 조회 기능 구현
  src/main/java/com/movelog/domain/news/application/NewsService.java
  src/main/java/com/movelog/domain/news/domain/repository/NewsRepository.java
  src/main/java/com/movelog/domain/news/dto/response/NewsCalendarRes.java
  src/main/java/com/movelog/domain/news/dto/response/TodayNewsStatusRes.java
  src/main/java/com/movelog/domain/news/presentation/NewsController.java
Labels: enhancement, feature ✨

#63 Merge develop to main
  src/main/java/com/movelog/domain/news/application/NewsService.java
  src/main/java/com/movelog/domain/news/domain/repository/NewsRepository.java
  src/main/java/com/movelog/domain/news/dto/response/NewsCalendarRes.java
  src/main/java/com/movelog/domain/news/dto/response/TodayNewsStatusRes.java
  src/main/java/com/movelog/domain/news/presentation/NewsController.java
Labels: feature ✨

#65 [FEAT] 날짜별 기록 조회 기능 구현
  src/main/java/com/movelog/domain/record/dto/response/RecordCalendarRes.java
  src/main/java/com/movelog/domain/record/presentation/RecordController.java
  src/main/java/com/movelog/domain/record/repository/RecordRepository.java
  src/main/java/com/movelog/domain/record/service/RecordService.java
Labels: feature ✨

#66 Merge develop to main
  src/main/java/com/movelog/domain/record/dto/response/RecordCalendarRes.java
  src/main/java/com/movelog/domain/record/presentation/RecordController.java
  src/main/java/com/movelog/domain/record/repository/RecordRepository.java
  src/main/java/com/movelog/domain/record/service/RecordService.java
Labels: feature ✨

#70 [FIX] 검색 시 검색어 요청 형식 변경
  src/main/java/com/movelog/domain/record/presentation/RecordController.java
  src/main/java/com/movelog/domain/record/service/RecordService.java
Labels: fix 🔧

#71 [FEAT] 사용자의 최신 기록 이미지 5개 조회 기능 구현
  src/main/java/com/movelog/domain/record/dto/response/Recent5RecordImagesRes.java
  src/main/java/com/movelog/domain/record/presentation/RecordController.java
  src/main/java/com/movelog/domain/record/repository/RecordRepository.java
  src/main/java/com/movelog/domain/record/service/RecordService.java
Labels: feature ✨

#75 [FEAT] 나의 단어 통계 조회를 위한 단어 검색 기능 구현
  .github/workflows/deploy.yml
  build.gradle
  src/main/java/com/movelog/MoveLogApplication.java
  src/main/java/com/movelog/domain/news/application/NewsService.java
  src/main/java/com/movelog/domain/record/application/KeywordService.java
  src/main/java/com/movelog/domain/record/application/RecordService.java
  src/main/java/com/movelog/domain/record/domain/repository/KeywordRepository.java
  src/main/java/com/movelog/domain/record/domain/repository/RecordRepository.java
  src/main/java/com/movelog/domain/record/dto/response/SearchKeywordInStatsRes.java
  src/main/java/com/movelog/domain/record/presentation/KeywordController.java
  src/main/java/com/movelog/domain/record/presentation/RecordController.java
  src/main/java/com/movelog/global/config/RedisConfig.java
Labels: feature ✨, CICD 🦋

#77 [FEAT] 사용자 기록 기반 단어 통계 정보 조회 기능 구현
  .github/workflows/deploy.yml
  build.gradle
  src/main/java/com/movelog/MoveLogApplication.java
  src/main/java/com/movelog/domain/news/application/NewsService.java
  src/main/java/com/movelog/domain/record/application/KeywordService.java
  src/main/java/com/movelog/domain/record/application/RecordService.java
  src/main/java/com/movelog/domain/record/domain/Keyword.java
  src/main/java/com/movelog/domain/record/domain/repository/KeywordRepository.java
  src/main/java/com/movelog/domain/record/domain/repository/RecordRepository.java
  src/main/java/com/movelog/domain/record/dto/response/MyKeywordStatsRes.java
  src/main/java/com/movelog/domain/record/dto/response/SearchKeywordInStatsRes.java
  src/main/java/com/movelog/domain/record/presentation/RecordController.java
  src/main/java/com/movelog/domain/record/presentation/StatsController.java
  src/main/java/com/movelog/global/config/RedisConfig.java
Labels: feature ✨, CICD 🦋

#79 [FIX] 통계 단어 검색 대상 데이터를 전체 사용자로 수정
  src/main/java/com/movelog/domain/record/application/KeywordService.java
  src/main/java/com/movelog/domain/record/domain/repository/KeywordRepository.java
Labels: fix 🔧

#81 [FEAT] 통계 단어 검색 시 최근 사용자가 기록한 단어 목록 조회 기능 구현
  src/main/java/com/movelog/domain/record/application/KeywordService.java
  src/main/java/com/movelog/domain/record/dto/response/RecommendKeywordInStatsRes.java
  src/main/java/com/movelog/domain/record/presentation/StatsController.java
Labels: feature ✨

#85 [FEAT] 모든 사용자 데이터 기반 특정 단어의 통계 정보 조회 기능 구현
  src/main/java/com/movelog/domain/record/application/KeywordService.java
  src/main/java/com/movelog/domain/record/domain/repository/RecordRepository.java
  src/main/java/com/movelog/domain/record/dto/response/AllUserKeywordStatsRes.java
  src/main/java/com/movelog/domain/record/presentation/StatsController.java
Labels: feature ✨

#86 [FIX] 기록 생성 시 이미지 null 허용
  src/main/java/com/movelog/domain/record/application/RecordService.java
  src/main/java/com/movelog/domain/record/presentation/RecordController.java
Labels: fix 🔧

#87 [FIX] 기록 생성 시 이미지 Optional 불가 문제 해결
  src/main/java/com/movelog/domain/record/application/RecordService.java
  src/main/java/com/movelog/domain/record/presentation/RecordController.java
Labels: fix 🔧
